## Python : Numpy


#### 1. Numpy: type, dtype, shape, dimension,size
- Data types are the same in an arrary.
- Rank : the (linearly independent)number of variables in a matrix.

In [2]:
# Create a rank one array with the array function
import numpy as np
a = np.array([7,8,9,10,11])
print(f'{a}\n{"objest type:":>12} {type(a)}\n {"data type:":>12} {a.dtype}\n{"shape":>12} \
{a.shape}\n{"dimension:":>12} {a.ndim}\n{"array size:":>12}{a.size}')
a1 = np.array([a])
print(a1.shape)

[ 7  8  9 10 11]
objest type: <class 'numpy.ndarray'>
   data type: int32
       shape (5,)
  dimension: 1
 array size:5
(1, 5)


In [12]:
# Create a rank two array : 2 dimensional array
b=np.array([[1.0,2,3,4,5],[8,9,10,11,12.2]])
print(f'{b}\n{"objest type:":>12} {type(b)}\n {"data type:":>12} {b.dtype}\n{"shape":>12} \
{b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12}{b.size}')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
objest type: <class 'numpy.ndarray'>
   data type: float64
       shape (2, 5)
  dimension: 2
 array size:10


In [13]:
# Create a rank two array : 3 dimensional array
c=np.array([[[1,2,3,4,5],[8,9,10,11,12]],[[4,5,6,7,8],[10,11,12,13,14]]])
print(f'{c}\n{"objest type:":>12}{type(c)} \n {"data type:":>12}{c.dtype} \n {"shape":>12} \
{c.shape}\n {"dimension:":>12}{c.ndim} \n{"array size:":>12}{c.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
objest type: <class 'numpy.ndarray'>
   data type: int32
       shape (2, 2, 5)
  dimension: 3
 array size:20


In [14]:
#an application 1
ac1=np.array([[[1,2,3,4,5],[8,9,10,11,12]]])
print(f'{ac1}\n {"object type:":>12}{type(ac1)} \n {"data type:":>12}{ac1.dtype} \n {"shape:":>12} \
{ac1.shape} \n {"dimension:":>12}{ac1.ndim} \n {"array size:":>12}{ac1.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
 object type:<class 'numpy.ndarray'> 
   data type:int32 
       shape: (1, 2, 5) 
   dimension:3 
  array size:10


In [16]:
#an application 2
ac2=np.array([[[1,2,3,4,5]]])
print(f'{ac2}\n {"object type:":>12}{type(ac2)} \n {"data type:":>12}{ac2.dtype} \n {"shape:":>12} \
{ac2.shape} \n {"dimension:":>12}{ac2.ndim} \n {"array size:":>12}{ac2.size}')

[[[1 2 3 4 5]]]
 object type:<class 'numpy.ndarray'> 
   data type:int32 
       shape: (1, 1, 5) 
   dimension:3 
  array size:5


#### 2. Numpy : special arrays and indexing

In [20]:
#filling arrays with specific values : all dtype = float64 except for 'full'
a_zeros = np.zeros((2,3))
print(a_zeros)
print()
a_ones = np.ones((2,4),dtype=int)
print(a_ones)
print()
a_full = np.full((2,5),7)
print(a_full)
print()
print(np.eye(3))
#정방향 

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]]

[[7 7 7 7 7]
 [7 7 7 7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#fitting an array with random floats : in the half-open interval[0.0,1.0].
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')

[[[0.79103153 0.71787978 0.89189949 0.15555884]
  [0.54701562 0.66318814 0.56397636 0.65069503]
  [0.78994592 0.08677598 0.74034228 0.98775283]]

 [[0.40682154 0.85159721 0.73544934 0.11553957]
  [0.22749814 0.66761632 0.45052008 0.63720474]
  [0.08494304 0.37877052 0.11821934 0.52789391]]]
float64


In [22]:
#array indexing
print(c)
print(c[1,0,4])
print(c[0,0,4])

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
5


#### 3.Numpy: flattening and making arrays with arange function

In [24]:
#flattening the c array in a row using for loop.
print(c,'\n')
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}\n')

#flattening : 4차원 배열을 1차원으로 바꾸는 것
print(np.array(c.flat))

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]] 

[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]

[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [25]:
#Making an array with arange with a same interval
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [26]:
h = np.arange(5,21,2)
print(h)
print(np.arange(1,21).reshape(2,10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [27]:
#Creating an array of equal space within a range
a_ss = np.linspace(0,1,11)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


#### 4.Numpy:Array operations
- Operations on all elements of arrays

In [29]:
#element-wise operations
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [30]:
#element-wise operations
print(np.add(xa,xb))
print(np.subtract(xa,xb))
print(np.multiply(xa,xb))
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[ 3  8]
 [15 24]
 [35 48]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [32]:
#inner product of matrix
xc = np.ones((2,1))
print(xc,xc.shape,xc.ndim)
print(xa.dot(xc))
print(np.dot(xb,xc))

[[1.]
 [1.]] (2, 1) 2
[[ 3.]
 [ 7.]
 [11.]]
[[ 7.]
 [11.]
 [15.]]


In [33]:
#inner product of matrix
xd = np.array([[1,2],[1,2]])
print(xd)

print(np.dot(xa,xd))
print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [34]:
# transposing and broadcasting
print(xa.T)
print(xb+3)
print(xb)
xb+=3
print(xb)


[[1 3 5]
 [2 4 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[3 4]
 [5 6]
 [7 8]]
[[ 6  7]
 [ 8  9]
 [10 11]]


#### 5.Numpy : Broadcasting
- Arithmetic operation between different shaped arrays

In [3]:
ya = np.arange(1,10).reshape(3,3)
print(ya)

yv1 = np.ones((3,1))
print(yv1)

yv2 = np.full((1,3),2)
print(yv2)

yc = ya + yv2
print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### 6. Numpy:Summary Statistcs

In [5]:
#Uses all elements in calculations
print(yc.sum(),yc.mean(),yc.min(),yc.var(),yc.std())
print(yc.argmax(),yc.argmin())#return index
print(yc.mean(axis=0),yc.mean(axis=1))

63 7.0 3 6.666666666666667 2.581988897471611
8 0
[6. 7. 8.] [ 4.  7. 10.]


#### 7.Numpy:Slicing,Flatten,and Stacking

In [6]:
karray=np.arange(21).reshape(3,7)
print(karray)

print(karray[0], karray[0,:4])
print(karray[:2])
print(karray[:2,:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] [0 1 2 3]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [8]:
karray=np.arange(21).reshape(3,7)
print(karray)
print(karray[[0,2]])
print(karray[:,[1,5]])
print(karray[:,1:5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [9]:
karray=np.arange(21).reshape(3,7)
print(karray)

fkarray=karray.flatten()
print(fkarray,fkarray.shape)

fkarray1=np.array(karray.flat)
print(fkarray1)

rfkarray=karray.reshape(1,21)
print(rfkarray,rfkarray.shape)

rfkarray.resize(3,7)
print(rfkarray,rfkarray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]] (1, 21)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [10]:
#staking
karray1 = karray[:,:3]
karray2 = karray[:,3:6]
karrayh = np.hstack([karray1, karray2])
print(karrayh)

karrayv = np.vstack([karray1, karray2])
print(karrayv)

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]]
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [ 3  4  5]
 [10 11 12]
 [17 18 19]]
